# /app/dockerfile-fastapi
# Using Debian bullseye-slim as base image
FROM python:3.11-slim-bullseye

WORKDIR /app

COPY ./requirements-fastapi.txt .
RUN apt-get update && apt-get install -y --no-install-recommends git && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir -r requirements-fastapi.txt

COPY . .

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]