# /app/dockerfile-gradio
# Using Debian bullseye-slim as base image
FROM python:3.11-slim-bullseye

# Set the working directory to /app
WORKDIR /app
COPY ./requirements-gradio.txt .

# Install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends --allow-change-held-packages \
        wget \
        git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir --upgrade pip setuptools

# Install Gradio and any other necessary dependencies
RUN pip install --trusted-host pypi.org -r requirements-gradio.txt

# Copy your Gradio interface script. Modify this if the path differs.
COPY src/ui/gradio_interface.py src/ui/gradio_interface.py

CMD ["python", "src/ui/gradio_interface.py"]

